### ISSUE TITLE
Loaded sounds sound different than when they were saved

### ISSUE THREAD

**Issue by ghost** [raysan5/rfxgen#1]
Left screenshot: before saving, right: after saving, exiting and loading back the same sound. Sounds different, notice the waveform:

![c7ycz0px4aedfj6](https://cloud.githubusercontent.com/assets/23236377/24116053/7b2dce36-0db6-11e7-8343-1f5a844ca05b.jpg)

**Comment by raysan5** [comment]
Hi @procedural!

Thank you very much for pointing this issue, it seems some generation parameter is not properly loaded... I bet it only happens with noise type waves... ;)

**Comment by procedural** [comment]
Not only! :)

![screenshot_2](https://cloud.githubusercontent.com/assets/23236377/24122248/2505cad4-0dcc-11e7-9c19-bb5448ae779d.png)

**Comment by raysan5** [comment]
Ouch... I thought it could be related to the random numbers generation for the noise wave... It seems to be something else, I'm checking it...

**Comment by raysan5** [comment]
Just for the record:

I verified saved sound parameters (`SaveSoundParams()`) are the same than loaded ones (`LoadSoundParams()`).

It seems something fails on wave generation ([`GenerateWave()`](https://github.com/raysan5/rFXGen/blob/master/src/rfxgen.c#L813)), after a quick look I marked some potential errors, need to review it more carefully...

It's quite weird beause after testing multiple waves, sometimes it works ok and sometimes fails... maybe some float rounding issue?

**Comment by raysan5** [comment]
Wow, keep checking `GenerateWave()` function but couldn't find the issue... so weird...

**Comment by procedural** [comment]
Afaik audio files are just arrays of bits, I'd watch an output array in memory and see how values change on each step of a debugger...

**Comment by raysan5** [comment]
yeah, you are right... it seems using my prinft() debugging won't be enough this time...

**Comment by TakoNekko** [comment]
That's what I did for saving & restoring noise waves. Although, I can't remember if that actually worked xD

```
typedef struct WaveParams {
    [...]
    int seed;
} WaveParams;
```
```
    if (regenerate || ((CheckCollisionPointRec(GetMousePosition(), (Rectangle){ 243, 48, 102, 362 })) && (IsMouseButtonReleased(MOUSE_LEFT_BUTTON))))
    {
        if (params.waveTypeValue == 3)
        {
            if (params.seed == 0)
            {
                params.seed = rand() % 0xFFFE;
            }

            srand(params.seed);
        }
			
        [...]
			
        if (params.waveTypeValue == 3)
        {
            srand(params.seed + time(NULL));
        }
    }
```

**Comment by raysan5** [comment]
I was working on it some time ago but I couldn't find the issue. Potential causes I checked:

 - Random seed not stored (as stated in last message)
 - Conditions comparing float values: `if (params.changeSpeedValue == 1.0f) arpeggioLimit = 0;`
 - Compiler issues on generated code

**Comment by raysan5** [comment]
ok, just stored random seed. It seems to work ok. Corrected in commit https://github.com/raysan5/rfxgen/commit/852954669b205e6d2d46aa4afb96c9fdd70874ff
