### ISSUE TITLE
Build instruction ?

### ISSUE THREAD

**Issue by dns** [raysan5/rfxgen#11]
How to build rfxgen using msvc/mingw toolchain?

**Comment by raysan5** [comment]
To build rfxgen, [raylib library](https://github.com/raysan5/raylib) is required.  Other external dependencies are already included with the project.

With MinGW on Windows, just compile with:
```
gcc -o rfxgen.exe rfxen.c external/tinyfiledialogs.c -s rfxgen_icon -Iexternal -lraylib -lopengl32 -lgdi32 -lcomdlg32 -lole32 -std=c99 -Wl,--subsystem,windows
```

**Comment by TaylorHere** [comment]
hi, I try to build this project on macOS, and  I found it's required #include "raygui.h", but I did't found raygui.h in raylib.

**Comment by raysan5** [comment]
@TaylorHere You can get raygui here: https://github.com/raysan5/raygui

**Comment by TaylorHere** [comment]
Is there a Build instruction for macOS? 
I've tried 
`clang -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL /opt/raylib/src/libraylib.a -std=c99 -I/opt/raylib/src -I../../raygui/src/ rfxgen.c`
but I got
`7 warnings generated.
Undefined symbols for architecture x86_64:
  "_tinyfd_inputBox", referenced from:
      _GuiFileDialog in rfxgen-22c5d8.o
  "_tinyfd_messageBox", referenced from:
      _GuiFileDialog in rfxgen-22c5d8.o
  "_tinyfd_openFileDialog", referenced from:
      _GuiFileDialog in rfxgen-22c5d8.o
  "_tinyfd_saveFileDialog", referenced from:
      _GuiFileDialog in rfxgen-22c5d8.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by TaylorHere** [comment]
this worked 
`clang -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL /opt/raylib/src/libraylib.a -std=c99 -I/opt/raylib/src -I../../raygui/src/ rfxgen.c external/tinyfiledialogs.c -o rfxgen`

**Comment by TaylorHere** [comment]
got a  display bug 
<img width="515" alt="image" src="https://user-images.githubusercontent.com/12156543/78587993-6b4b7900-7870-11ea-9f42-6a05c829a85c.png">

**Comment by raysan5** [comment]
@TaylorHere it's related to HighDPI on macOS, not solved yet... actually, it also depends on macOS version... try with enable `SUPPORT_HIGH_DPI` config flag on `raylib/src/config.h`, you will need to recompile raylib library...

**Comment by mTvare6** [comment]
@TaylorHere I get the following error trying to compile like that
```bash
clang -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL /usr/local/Cellar/raylib/3.5.0/lib/libraylib.a -std=c99 -I/opt/raylib/src -I../../raygui/src/ rfxgen.c external/tinyfiledialogs.c -o rfxgen
```
```cpp
In file included from rfxgen.c:98:
./gui_file_dialogs.h:141:42: error: implicit declaration of function 'tinyfd_openFileDialog' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        case DIALOG_OPEN: tempFileName = tinyfd_openFileDialog(title, fileName, filterCount, filterSplit, message, 0); break;
                                         ^
./gui_file_dialogs.h:141:40: warning: incompatible integer to pointer conversion assigning to 'const char *' from 'int' [-Wint-conversion]
        case DIALOG_OPEN: tempFileName = tinyfd_openFileDialog(title, fileName, filterCount, filterSplit, message, 0); break;
                                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./gui_file_dialogs.h:142:42: error: implicit declaration of function 'tinyfd_saveFileDialog' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        case DIALOG_SAVE: tempFileName = tinyfd_saveFileDialog(title, fileName, filterCount, filterSplit, message); break;
                                         ^
./gui_file_dialogs.h:142:42: note: did you mean 'tinyfd_openFileDialog'?
./gui_file_dialogs.h:141:42: note: 'tinyfd_openFileDialog' declared here
        case DIALOG_OPEN: tempFileName = tinyfd_openFileDialog(title, fileName, filterCount, filterSplit, message, 0); break;
                                         ^
./gui_file_dialogs.h:142:40: warning: incompatible integer to pointer conversion assigning to 'const char *' from 'int' [-Wint-conversion]
        case DIALOG_SAVE: tempFileName = tinyfd_saveFileDialog(title, fileName, filterCount, filterSplit, message); break;
                                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./gui_file_dialogs.h:143:39: error: implicit declaration of function 'tinyfd_messageBox' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        case DIALOG_MESSAGE: result = tinyfd_messageBox(title, message, "ok", "info", 0); break;
                                      ^
./gui_file_dialogs.h:144:47: error: implicit declaration of function 'tinyfd_inputBox' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        case DIALOG_TEXTINPUT: tempFileName = tinyfd_inputBox(title, message, ""); break;
                                              ^
./gui_file_dialogs.h:144:45: warning: incompatible integer to pointer conversion assigning to 'const char *' from 'int' [-Wint-conversion]
        case DIALOG_TEXTINPUT: tempFileName = tinyfd_inputBox(title, message, ""); break;
        ```
