### ISSUE TITLE
[File System] Case sensitivity in file names

### ISSUE THREAD

**Issue by TakoNekko** [raysan5/rfxgen#12]
rfxGen only import files with lower case file extensions. But in Windows (and MacOS), file names are usually treated in a case insensitive manner.

I'd recommend replacing instances like `strcmp(GetExtension(fileName),"rfx") == 0` with `IsFileExtension(fileName, "rfx")` and update `IsFileExtension` to perform a case insensitive comparison on Windows.

**Comment by raysan5** [comment]
Reviewing it on raylib per https://github.com/raysan5/raylib/issues/499

**Comment by raysan5** [comment]
Implemented in commit https://github.com/raysan5/raylib/commit/9318dc98ce647acd9a718243555996618e95b959
