### ISSUE TITLE
Black screen when opened on Linux

### ISSUE THREAD

**Issue by TeddyDD** [raysan5/rfxgen#13]
OS: Arch 64 bit
When I run rfxgen empty black window appears. 
Tested on following versions:
-  `c132ff` build from source with raylib built from master (`61e0e4` commit)
- Itch.io builds (both dark and light theme

I tested both options with Intel graphics as well as primusun (Nvidia GPU)

Windows build works via Wine. I tried to run few Raylib examples, they work fine.

cli output:
```
./rfxgen_dark                                                                                                       pon, 19 mar 2018, 15:00:49
INFO: Initializing raylib (v1.9.6-dev)
INFO: Display device initialized successfully
INFO: Display size: 1600 x 900
INFO: Render size: 500 x 500
INFO: Screen size: 500 x 500
INFO: Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: OpenGL 3.3 Core profile supported
INFO: GPU: Vendor:   Intel Open Source Technology Center
INFO: GPU: Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
INFO: GPU: Version:  4.2 (Core Profile) Mesa 17.3.6
INFO: GPU: GLSL:     4.20
INFO: Number of supported extensions: 175
INFO: [EXTENSION] DXT compressed textures supported
INFO: [EXTENSION] ETC2/EAC compressed textures supported
INFO: [EXTENSION] Anisotropic textures filtering supported (max: 16X)
INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [SHDR ID 1] Shader compiled successfully
INFO: [SHDR ID 2] Shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: [CPU] Default buffers initialized successfully (lines, triangles, quads)
INFO: [VAO ID 1] Default buffers VAO initialized successfully (lines)
INFO: [VAO ID 2] Default buffers VAO initialized successfully (triangles)
INFO: [VAO ID 3] Default buffers VAO initialized successfully (quads)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: [TEX ID 2] Default font loaded successfully

```

Screenshot:
![zrzut ekranu z 2018-03-19 15-00-56](https://user-images.githubusercontent.com/4397533/37600011-6d70d7ae-2b86-11e8-926f-e4a52ff3d31c.png)

**Comment by raysan5** [comment]
weird... I tested it on Ubuntu and it worked ok. Examples worked ok on your system? I imagine you use X11 for Windowing...

**Comment by TeddyDD** [comment]
Yes, I use x11. Examples are working fine, I have not tried all of them. I'll try to run it on my other laptop.

**Comment by TeddyDD** [comment]
Audio examples are not working, the same problem. I'v got alsa-lib, alsa-oss lib32-alsa-lib and lib32-alsa-oss packages installed.

**Comment by raysan5** [comment]
ok, so here it is the problem... something breaks silently on audio initialization... raylib uses mini_al library for audio, maybe @mackron could shed some light on this issue...

**Comment by mackron** [comment]
Strange... So it doesn't actually crash, just a frozen blank window? I have an Arch virtual machine which I will try later tonight.

This probably won't help, but just recently I fixed a random hang on BSD which was caused by my runtime linking of pthreads. Could you try passing in -lpthread when compiling?

And there's no mini_al error messages?

Will take a more detailed look when I get home from work.

**Comment by raysan5** [comment]
Hey @mackron! Thanks for looking into this! I compiled it on Ubuntu (latest version) and current compilation line was (GCC 7.2):
```
gcc -o rfxgen rfxgen.c external/tinyfiledialogs.c -s -Iexternal -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -std=c99 -no-pie -D_DEFAULT_SOURCE
```
On Ubuntu it works perfectly. Just for reference, this is the expected raylib output (Windows version):
```
INFO: Initializing raylib (v1.9.6-dev)
INFO: Display device initialized successfully
INFO: Display size: 2160 x 1440
INFO: Render size: 500 x 500
INFO: Screen size: 500 x 500
INFO: Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: OpenGL 3.3 Core profile supported
INFO: GPU: Vendor:   Intel
INFO: GPU: Renderer: Intel(R) HD Graphics 4400
INFO: GPU: Version:  3.3.0 - Build 20.19.15.4568
INFO: GPU: GLSL:     3.30 - Build 20.19.15.4568
INFO: Number of supported extensions: 219
INFO: [EXTENSION] DXT compressed textures supported
INFO: [EXTENSION] ETC2/EAC compressed textures supported
INFO: [EXTENSION] Anisotropic textures filtering supported (max: 16X)
INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [SHDR ID 1] Shader compiled successfully
INFO: [SHDR ID 2] Shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: [CPU] Default buffers initialized successfully (lines, triangles, quads)
INFO: [VAO ID 1] Default buffers VAO initialized successfully (lines)
INFO: [VAO ID 2] Default buffers VAO initialized successfully (triangles)
INFO: [VAO ID 3] Default buffers VAO initialized successfully (quads)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: [TEX ID 2] Default font loaded successfully
INFO: Audio device initialized successfully: Default Playback Device
INFO: Audio backend: mini_al / WASAPI
INFO: Audio format: 32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
INFO: Audio channels: 2 -> 2
INFO: Audio sample rate: 44100 -> 48000
INFO: Audio buffer size: 1197
INFO: [FBO ID 1] Framebuffer object created successfully
INFO: [FBO ID 2] Framebuffer object created successfully
INFO: Target time per frame: 16.667 milliseconds
```

**Comment by mackron** [comment]
Pull Request submitted: https://github.com/raysan5/raylib/pull/510

This is related to this commit I did a while ago in the mini_al repository: https://github.com/dr-soft/mini_al/commit/ca3a024212680d28ceb1be15eb7f610869c137e1. There's a whole bunch of changes coming through for mini_al, so when I get the new version out I'll integrate it into raylib for you (if you want) because there's quite a few bug fixes and improvements in there. Mid-April is the target.

Let me know if this still isn't fixed and I'll take another look at it.

(As a side note, I was actually wanting to build a tool like this - you beat me to it!)

**Comment by raysan5** [comment]
Hey @mackron! Many thanks for the quick fix! :D

I won't have access until Thursday to the Ubuntu PC, I'll try then.

 >  There's a whole bunch of changes coming through for mini_al, so when I get the new version out I'll integrate it into raylib for you (if you want)

Feel free to integrate any mini_al update! You're welcome!

 > (As a side note, I was actually wanting to build a tool like this - you beat me to it!)

Actually, just ported (and mostly rewrote) the amazing [sfxr](http://www.drpetter.se/project_sfxr.html) to raylib... it was a [raygui](https://github.com/raysan5/raygui) interface system test tool. I'm not an audio expert so, probably, it can be improved in multiple ways.

**Comment by TeddyDD** [comment]
@mackron thanks for the fix, audio examples are working now when compiled form raylibs's master :)

@raysan5 I tried compiling rfxgen with `gcc -o rfxgen rfxgen.c external/tinyfiledialogs.c -s -Iexternal -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -L../raylib/release/libs/linux -std=c99 -no-pie -D_DEFAULT_SOURCE`

This time it does not hangs on audio initialization, it just crashes
```
env LD_LIBRARY_PATH=../raylib/release/libs/linux/ ./rfxgen
INFO: Initializing raylib (v1.9.6-dev)
INFO: Display device initialized successfully
INFO: Display size: 1600 x 900
INFO: Render size: 500 x 500
INFO: Screen size: 500 x 500
INFO: Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: OpenGL 3.3 Core profile supported
INFO: GPU: Vendor:   Intel Open Source Technology Center
INFO: GPU: Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
INFO: GPU: Version:  4.2 (Core Profile) Mesa 17.3.6
INFO: GPU: GLSL:     4.20
INFO: Number of supported extensions: 175
INFO: [EXTENSION] DXT compressed textures supported
INFO: [EXTENSION] ETC2/EAC compressed textures supported
INFO: [EXTENSION] Anisotropic textures filtering supported (max: 16X)
INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [SHDR ID 1] Shader compiled successfully
INFO: [SHDR ID 2] Shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: [CPU] Default buffers initialized successfully (lines, triangles, quads)
INFO: [VAO ID 1] Default buffers VAO initialized successfully (lines)
INFO: [VAO ID 2] Default buffers VAO initialized successfully (triangles)
INFO: [VAO ID 3] Default buffers VAO initialized successfully (quads)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: [TEX ID 2] Default font loaded successfully
INFO: Audio device initialized successfully: Default Playback Device
INFO: Audio backend: mini_al / ALSA
INFO: Audio format: 32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
INFO: Audio channels: 2 -> 2
INFO: Audio sample rate: 44100 -> 44100
INFO: Audio buffer size: 1100
Segmentation fault (core dumped)
```

**Comment by raysan5** [comment]
Seems that potential issue is located [at this point](https://github.com/raysan5/raylib/blob/master/src/audio.c#L898). I'm checking it more carefully...

**Comment by TeddyDD** [comment]
I tested rfxgen on another Arch machine, and reproduced this isssue. I also tried building newest raylib form master, the same thing.

On the other hand I tried rfxgen from Itch on my second laptop with Void Linux installed and it works like a charm :)

**Comment by raysan5** [comment]
Hi @TeddyDD! Thanks for the feedback! 

After some investigation, I'm pretty convinced that issue is located in [mentioned point](https://github.com/raysan5/raylib/blob/master/src/audio.c#L916), most probably in `mal_convert_frames()`, checking [mini_al base code](https://github.com/dr-soft/mini_al/blob/dev/mini_al.h#L18140), that function returns a `mal_uint64` while in `LoadSoundFromWave()` it's stored in `mal_uint32`...

But mini_al is under development and [dev branch](https://github.com/dr-soft/mini_al/tree/dev) is +100 commits ahead master, so that function is probably already reviewed (or even redesigned) as @mackron wrote:

 > There's a whole bunch of changes coming through for mini_al, so when I get the new version out I'll integrate it into raylib for you (if you want) because there's quite a few bug fixes and improvements in there. Mid-April is the target.

We can wait for the update and see if it solves the issue.

**Comment by mackron** [comment]
Seems strange that this particular part of the code would cause a platform-specific crash. But, indeed, that part of mini_al has been redesigned so it may already be fixed.

@raysan5 Is the version from Itch built with the old OpenAL code or with the mini_al code?

**Comment by raysan5** [comment]
@mackron, itch.io version uses latest raylib version from the day it was uploaded, it already uses mini_al.

**Comment by shackra** [comment]
Mate, I have this issue too as described (a black window), I'm using Arch Linux with GNOME 3.28.0. The version I'm having troubles with is the one coming from Itch.io.

**Comment by raysan5** [comment]
Hi @shackra, just got an old computer and tried to install Arch to address this issue. Unfortunately, Anarchy installer keeps failing when veryfying some package keys (really annoying). I'll try to upload a new version ASAP.

**Comment by TeddyDD** [comment]
@raysan5 try Antergos ;) Pretty nice installer for Arch

**Comment by mackron** [comment]
@raysan5 I've got a branch set up in preparation for updating raylib with the latest updates to mini_al. Would you be able to try this branch and see if that fixes this problem? https://github.com/mackron/raylib/tree/dr/mini_al

Note that this branch isn't ready for merging into raylib just yet, but I thought it would be good to try it just in case it fixes this problem so we can stop looking.

**Comment by mackron** [comment]
I got this working on an old out-of-date Antergos (64-bit) on a virtual machine with my updates, but it would be good if somebody else could verify.

**Comment by raysan5** [comment]
@mackron thank you very much for taking care of this issue! I'll check it next week on a current Antergos on real hardware. I'll let you know!

**Comment by raysan5** [comment]
Just installed Antergos and recompiled current github rfxgen with current github raylib and it worked perfectly on my computer:

![screenshot from 2018-04-25 12-03-09](https://user-images.githubusercontent.com/5766837/39366607-b2c4a2f0-4a34-11e8-88c9-11e609d7b35b.png)

And rfxgen running ok:

![screenshot from 2018-04-27 15-55-25](https://user-images.githubusercontent.com/5766837/39366629-c15310ae-4a34-11e8-907c-152f782ff8ea.png)

I uploaded generated [rFXGen to itch.io](https://raysan5.itch.io/rfxgen) just in case.

**Comment by shackra** [comment]
Installed and I'm getting a crash: [cave-390402f3-0f3d-46a6-971f-5da69ca5f6b9.txt](https://github.com/raysan5/rfxgen/files/1956421/cave-390402f3-0f3d-46a6-971f-5da69ca5f6b9.txt)

**Comment by mackron** [comment]
I'm getting the same thing on my out of date Antergos installation. I think it's because Arch only started rolling out Glibc 2.27 a week or so ago.

`./rfxgen-arch-64bit: /usr/lib/libm.so.6: version `GLIBC_2.27' not found (required by ./rfxgen-arch-64bit)`

@shackra Try updating Arch if you can.

@raysan5 I'm also updating my Antergos installation as I write this - I'll let you know if that fixes it (so long as the upgrade doesn't break my GUI which it has a tendency to do...)

**Comment by shackra** [comment]
Updating Arch made it! :)

![captura de pantalla de 2018-04-27 23-34-28](https://user-images.githubusercontent.com/1055216/39392470-999ee1a2-4a73-11e8-956a-02fabcb51c97.png)

**Comment by raysan5** [comment]
Awesome! :D 

@mackron thank you very much for tracking this issue and finding the solution!

@TeddyDD does it work for you?

**Comment by TeddyDD** [comment]
I'll test ASAP and let you know later today

**Comment by TeddyDD** [comment]
It works :D
