### ISSUE TITLE
User interface is tiny on high dpi screens

### ISSUE THREAD

**Issue by ducaale** [raysan5/rfxgen#16]
# Environment
I am using Windows 10 with resolution of 1920x1080 and 150% dpi scaling.

# Expected behavior
rfxgen UI size should change depending on the selected dpi scale.

# Actual behavior
rfxgen UI does not respect the selected DPI scale

**Comment by raysan5** [comment]
@ducaale rFXGen uses a pixel-art gui style, if automatically scaled to highDPI everything gets blurred. 

I added a x2-screen-size button in case of highDPI. I know it's not the best solution but supporting highDPI (without blurring) would require redesigning all the interface. No plans for the moment.
