### ISSUE TITLE
Trying to export a .wav without the extension doesn't save anything

### ISSUE THREAD

**Issue by vgf89** [raysan5/rfxgen#19]
rFXGen v2.1

Ideally if I type in a file name without the .wav (but .wav is selected as the filetype), it should add .wav to it and save it. As it is right now, it just doesn't save anything, which is annoying if I'm trying to quickly open and export a bunch of files.

**Comment by raysan5** [comment]
Did you compile current source code? I thought I already fixed that issue... 🤔
