### ISSUE TITLE
Doesn't show a version number anywhere

### ISSUE THREAD

**Issue by EJSainz** [raysan5/rfxgen#2]
Thus I can't let the developer know which version does have a bug :-( .

**Comment by raysan5** [comment]
Hi @EJSainz! Thank you very much for the review (and the bugs... :P). I'm busy finishing new raylib v1.7 but I'll take care of them after that.

About rFXGen version, is marked on [source](https://github.com/raysan5/rFXGen/blob/master/src/rfxgen.c) but it's a good idea to also display it on the tool... I'll look for some corner...

**Comment by raysan5** [comment]
Corrected in commit https://github.com/raysan5/rfxgen/commit/2e67a45d69757cef456b0453c8bd1a8bcc7f6312
