### ISSUE TITLE
Exported .wav does not match the editor

### ISSUE THREAD

**Issue by Antilurker77** [raysan5/rfxgen#21]
In the editor:
![image](https://user-images.githubusercontent.com/34405647/146208034-140ebe92-85df-4d83-8b58-21a6fef3bf43.png)

In Audacity:
![image](https://user-images.githubusercontent.com/34405647/146208179-29e2b86e-1e67-4b2c-925b-07610ecd6961.png)

**Comment by raysan5** [comment]
@Antilurker77 I've been investigating this issue and it seems it fails in `ExportWave()` and only for float 32bit data. For 8/16bit it seems to work ok. The related code that exports that data is provided by `drwav` library:
```c
        drwav wav = { 0 };
        drwav_data_format format = { 0 };
        format.container = drwav_container_riff;
        format.format = DR_WAVE_FORMAT_PCM;
        format.channels = wave.channels;
        format.sampleRate = wave.sampleRate;
        format.bitsPerSample = wave.sampleSize;

        void *fileData = NULL;
        size_t fileDataSize = 0;
        success = drwav_init_memory_write(&wav, &fileData, &fileDataSize, &format, NULL);
        if (success) success = (int)drwav_write_pcm_frames(&wav, wave.frameCount, wave.data);
        drwav_result result = drwav_uninit(&wav);

        if (result == DRWAV_SUCCESS) success = SaveFileData(fileName, (unsigned char *)fileData, (unsigned int)fileDataSize);

        drwav_free(fileData, NULL);
```
Maybe @mackron could know if there is any issue with the export? I'm attaching a zip with the `sound.rfx` to regenerate the sound with rFXGen and also the sound exported as `8bit`, `16bit` and `32bit` wav files: [sound.zip](https://github.com/raysan5/rfxgen/files/7757520/sound.zip).

**Comment by mackron** [comment]
The issue here is the format. It needs to be IEEE instead of PCM for floating point.

**Comment by raysan5** [comment]
@mackron Wow! Superfast answer! Thank you very much! :D

**Comment by raysan5** [comment]
Reviewed in raylib commit https://github.com/raysan5/raylib/commit/58f2bf4181299c70e30440b5734544114d77e706
