### ISSUE TITLE
make the app accessible for screen readers

### ISSUE THREAD

**Issue by king-dahmanus** [raysan5/rfxgen#22]
this app isn't accessible for screen readers(programs for blind people which read text on the screen), I really wanna use this app, but the screen reader can't read it. I don't know what gui lib this uses, and I don't have any knowledge of gui libs accessibility except in python(wxpython). As I said, I'd love to use this app, but I can't. Hope this gets fixed soon. Regards and thanks for makin this app

**Comment by raysan5** [comment]
I'm afraid this improvement is out-of-scope for the moment. `rFXGen` uses `raygui` immediate-mode-gui library and functionality is very limited, actually it just draws rectangles and text using OpenGL. 

Text is just plain char arrays in C language, I don't know how that data can be provided to a screen reader software.
