### ISSUE TITLE
.sfs file not loading correctly in rfxgen

### ISSUE THREAD

**Issue by return2monki** [raysan5/rfxgen#24]
[laser.zip](https://github.com/raysan5/rfxgen/files/8977592/laser.zip)

This was the first .sfs file I tried and it doesn't seem compatible.

I don't mind no compatibility but just reporting it as the readme says it is.

**Comment by return2monki** [comment]
I just noticed that the laser/shoot generation in rfxgen sounds way off, that probably has to do with why it doesn't load correctly. It sounds more like the pickup coin sound

**Comment by raysan5** [comment]
Just removing .sfs files support.
