### ISSUE TITLE
2x screen size toggle makes the bottom text appear off-screen

### ISSUE THREAD

**Issue by return2monki** [raysan5/rfxgen#25]
Once again not the biggest deal, and fixed by hiding task bar or dragging the title bar upwards. But it would be nice if it all fit on screen without doing that.

Windows 10

**Comment by raysan5** [comment]
@return2monki Actually I was planning to remove that button in next release. I'll see what to do with that...

**Comment by return2monki** [comment]
I suggest changing size to 1.5 if you still don't know what to do with it, don't even need a toggle at that size really.

**Comment by raysan5** [comment]
Toggle button is being removed and added a shortcut, just in case.

**Comment by turbohz** [comment]
For anyone looking, shortcut is `LCTRL+F` (found in the [?] help screen)
