### ISSUE TITLE
Ability to right-click a slider to reset it back to the original point

### ISSUE THREAD

**Issue by return2monki** [raysan5/rfxgen#26]
This feature from sfxr doesn't seem to be here, just a suggestion as this one is quite useful imo.

**Comment by raysan5** [comment]
@return2monki mmh... this could be more tricky than expected, rfxgen uses raygui and it doesn't implement that functionality. Also, origin could be left, center, right or random point. raygui does not store that data an rfxgen would need to keep a copy of all data only for that functionality.

I'm afraid the implementation cost overpasses the usefulness of the feature.

**Comment by raysan5** [comment]
@return2monki Actually that's what I meant: you have to keep a copy of all sliders data to be able to modify them and reset them to original data copy. I find it overengineering for a simple tool like this one.

**Comment by return2monki** [comment]
Fair enough
