### ISSUE TITLE
Error while building on Linux

### ISSUE THREAD

**Issue by jJit0** [raysan5/rfxgen#31]
Hi,

When trying to build the new version v3.1 on linux, I get this error:
```
/usr/bin/ld: /tmp/user/0/ccg9Nw8T.o: in function `GuiTextBoxMulti':
rfxgen.c:(.text+0x5350): undefined reference to `GetCodepointNext'
/usr/bin/ld: /tmp/user/0/ccg9Nw8T.o: in function `GetTextWidth':
rfxgen.c:(.text+0xbab7): undefined reference to `GetCodepointNext'
/usr/bin/ld: /tmp/user/0/ccg9Nw8T.o: in function `GuiDrawText':
rfxgen.c:(.text+0xc5dc): undefined reference to `GetCodepointNext'
collect2: error: ld returned 1 exit status
```

I build it using this oneliner from one of the previous issues:
`gcc -o rfxgen rfxgen.c external/tinyfiledialogs.c -s -Iexternal -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -L../raylib/release/libs/linux -std=c99 -no-pie -D_DEFAULT_SOURCE`

Although, raylib is already installed, so any ideas ?

**Comment by raysan5** [comment]
@jJit0 You have to use latest version of raylib from github master branch. `GetCodepointNext()` was added a couple of weeks ago.
