### ISSUE TITLE
Root cause of sound effect difference between rfxgen and sfxr?

### ISSUE THREAD

**Issue by lesleyrs** [raysan5/rfxgen#34]
I spent some time comparing sfxr and rfxgen sound parameters and they seem to be exactly the same. In the application the sliders appear in the correct position as well. This is not related to loading or saving either.

So if it's not the parameters or loading being incorrect then what causes the laser and hit sounds to be very different? The other ones work the same so it's really strange to me.

**Comment by raysan5** [comment]
@lesleyrs `rfxgen` implementation in based on `sfxr` but most of the code was rewritten and adapted, there could be small diferences that translate into a totally different sound generated. Also, raylib current random number generator is very limited (uses `rand()`), it could be reviewed in the future.

**Comment by lesleyrs** [comment]
I checked and sfxr uses rand() as well, the problem is probably something subtle so it's going to be hard to fix 😢

**Comment by raysan5** [comment]
@lesleyrs After some investigation detected a big issue with `RFXGEN_RAND(0, 1)` condition, returning always 0. So multiple parameters were never updated on random generations. Now should work as expected.
