### ISSUE TITLE
Undo/redo?

### ISSUE THREAD

**Issue by jelledv49** [raysan5/rfxgen#35]
Hey,

Thanks for this awesome tool! Currently I'm trying it out, and I was wondering whether it's possible to undo/redo actions? I'm unfamiliar with the properties that can be tuned (I don't know much about sound), so I just try them out, but it's quite time consuming to remember the previous value each time, then try tuning it, and then set it back manually. 

While I try to remember the original value each time, I sometimes forget. Alternatively, I could save each time I make a change, but then some sort of file versioning would be necessary, but it wouldn't be as easy as undo/redo.

**Comment by raysan5** [comment]
Hi @jelledv49! Implementing an undo/redo system would imply some work and additional complexity for the tool. For the moment it is out-of-scope for this small tool.
