### ISSUE TITLE
Zoomed in UI makes tooltips and the report issue window inaccessible

### ISSUE THREAD

**Issue by InsigMath** [raysan5/rfxgen#38]
**Version**: rfxgen_v4.2_win_x64

**Operating System**: Windows 10

**Description of Problem**:  When you click LCTRL-F to zoom in the top right buttons in the UI (Show Help Window/Show Info Window/Report an Issue) tooltips get cut out. Also when you click the 
"Report an Issue" button zoomed in the window appears at the bottom right as seen in the image below and there does not seem to be a way to move the report window to the center.

![2024-04-24 10_01_39-rFXGen v4 2 _ A simple and easy-to-use fx sounds generator](https://github.com/raysan5/rfxgen/assets/2395535/39bf6f78-734b-4d5a-8b51-e119167f0824)

**Comment by raysan5** [comment]
@InsigMath Thanks for reporting, fixed the Report Issue Window but the tooltips require some more work...

**Comment by raysan5** [comment]
After lot of review, I'm afraid the tooltip issue will be left as design, it only happens on this specific side case (scaling window to draw a scaled render texture) and it is not that dramatic.
