### ISSUE TITLE
Exports WAV files without extension.

### ISSUE THREAD

**Issue by EJSainz** [raysan5/rfxgen#4]
On Windows 10, when using the version downloaded from itch.io .

I've exported two WAV files so far, but both had no extension, and thus the OS wouldn't play them.

After renaming and adding the .wav extension, files worked properly.

**Comment by raysan5** [comment]
Corrected in commit https://github.com/raysan5/rfxgen/commit/2e67a45d69757cef456b0453c8bd1a8bcc7f6312
