### ISSUE TITLE
Doesn't sound and crashes after unpligging the headphones

### ISSUE THREAD

**Issue by EJSainz** [raysan5/rfxgen#5]
On Windows 10, when using the version downloaded from itch.io .

When I unplug the headphones, the OS automatically selects my screen speakers as the audio output device. RFXGen is still working, but not a sound will play.

If I try to close the application then, it will freeze, forcing me to kill it from the Task Manager.

**Comment by raysan5** [comment]
That issue is related to audio context lost after device initialization. Audio devices are managed with `OpenAL Soft`... need to investigate it but doesn't seem to be an easy solution...

**Comment by raysan5** [comment]
It depends on audio system, should be ok on latest release.

**Comment by Shufel** [comment]
how to fix this problem?
I exp same problem.

**Comment by raysan5** [comment]
Hi @Shufel, are you using latest rfxgen from itch.io?

What are your system specs (CPU, GPU, OS)?

**Comment by Shufel** [comment]
Thanks to reply.
I solved this problem.
just my version is old. lol
