### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by EJSainz** [raysan5/rfxgen#6]
There are two interesting links to github on the left column of RFXGen, but clicking them won't work :-( .

**Comment by raysan5** [comment]
Just some notes on how to do it from C:
```c
// OPTION 01: system(): portable, explorer must be on system path, blocking
system("explorer http://www.raylib.com");

// OPTION 02: ShellExecute(): windows only, uses default system explorer, non-blocking
ShellExecute(NULL, "open", "http://www.raylib.com", NULL, NULL, SW_SHOWNORMAL);
```

`OPTION 02` is better for this tool.

**Comment by raysan5** [comment]
Implemented in commit https://github.com/raysan5/rfxgen/commit/0c6432e71851d5f5ec92ce8dd197dcd2ff04a47a
