### ISSUE TITLE
App crashs if you click in Export .Wav and then cancel

### ISSUE THREAD

**Issue by RafaelOliveira** [raysan5/rfxgen#7]
Open the app, click in "Export .Wav", and then cancel. It will crash.

Tested in linux, compiled from the source, and also from wine. Wine is not the best source to test, but the rest of app works well in both linux native and wine.

I don't know much about makefiles, but I took the makefile to compile the template advance_game (in raylib), and changed the part to compile the screens to compile the tinyfiledialogs, and worked.

**Comment by raysan5** [comment]
Hi @RafaelOliveira, just tested it on Windows platform and it works ok, no crash.

It could be related to [tinyfiledialog](https://sourceforge.net/projects/tinyfiledialogs/) library, I got some crashes in the past... In any case, I'll do some tests.

**Comment by raysan5** [comment]
Corrected in commit https://github.com/raysan5/rfxgen/commit/2e67a45d69757cef456b0453c8bd1a8bcc7f6312
